<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Configurations>Debug</Configurations>
    <OutputType>Library</OutputType>
    <RootNamespace>Starlight</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Starlight</AssemblyName>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <DocumentationFile>bin\Debug\net6.0-windows\Starlight.xml</DocumentationFile>
    <WarningLevel>0</WarningLevel>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Remove="EncodedAssets\OriginalFiles\**" />
    <EmbeddedResource Include="*.csv" />
    <EmbeddedResource Include="Assets\**">
      <LogicalName>$([System.String]::Copy('$(RootNamespace).Assets.%(RecursiveDir)%(FileName)%(Extension)').Replace('\', '.').Replace('/', '.'))</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Remove="start.bat" />
    <None Remove="start.sh" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="../Libs/*.dll">
    </Reference>
  </ItemGroup>
</Project>
