<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Configurations>Debug</Configurations>
    <OutputType>Library</OutputType>
    <RootNamespace>StarlightExampleExpansion</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>StarlightExampleExpansion</AssemblyName>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Essentials\Essentials.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="../Libs/*.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\**">
      <LogicalName>$([System.String]::Copy('$(RootNamespace).Assets.%(RecursiveDir)%(FileName)%(Extension)').Replace('\', '.').Replace('/', '.'))</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
